// app/layout.js (RootLayout)
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";
import Sidebar from "@/app/dashboard/_components/DashboardBox"; // 👈 import sidebar

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Next Gen Hire",
  description: "Generated by Shubham Kasture",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* Fixed, responsive sidebar */}
          <Sidebar />

          {/* Main content: full width on mobile, shifted right on desktop */}
          <div className="sm:ml-64 ml-0">
            <Toaster />
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
